# The database of an ANKI user usually can be find at <ANKI installation directory>/<user>/

# Google TTS setup
# PATH to google app credential file. The credential file can be downloaded from Google Cloud Console when 
# you have registered the service.
GOOGLE_TTS_ENABLE: True
GOOGLE_APPLICATION_CREDENTIALS: ~/.google/myChineseTTS-5ab978b84843.json
GOOGLE_TTS_LANAGUAGE_CODE: "cmn-CN"
GOOGLE_TTS_VOICE_NAME: "cmn-CN-Wavenet-A"
GOOGLE_TTS_SPEAKING_RATE: 0.9
GOOGLE_TTS_PARAGRAPH_BREAK_TIME: "1s"

#You can set the TTS_OUTPUT_DIR to ANKI media directory. 
#If you don't choose to put tts audio to ANKI media directory,
#you will have to copy the generated audio to ANKI media folder.
TTS_OUTPUT_DIR: "~/tts.database"

#ANKI Note/Card setup
ANKI_CHINESE_WORD_NOTE_TYPE: ["字词", "拼音", "笔画", "词组", "去字词组", "成语", "去字成语", "标准解释", "字词频", "例句", "辅助_修改读音"]

